Add a chi example for sync users
Altinity/clickhouse-operator pull request #1304
Opened 2024-01-10 01:23 UTC by ccsxs

I submit a yuml template for migrating users when expanding capacity, so that people in need can use it.

2024-01-10 14:14 UTC, Slach requested changes

2024-01-10 14:14 UTC, Slach commented on docs/chi-examples/02-templates-07-syncUser.yaml
> +      dataVolumeClaimTemplate: localpvc-storage
remove unnecessary details, 
let's rename to `data-pvc-template`

2024-01-10 14:14 UTC, Slach commented on docs/chi-examples/02-templates-07-syncUser.yaml
> +    zookeeper:
lets add comment 
```yaml
# deploy zookeeper separatelly, look examples in https://github.com/Altinity/clickhouse-operator/blob/master/deploy/zookeeper/quick-start-persistent-volume/zookeeper-1-node.yaml
```

2024-01-10 14:14 UTC, Slach commented on docs/chi-examples/02-templates-07-syncUser.yaml
> +          storageClassName: my-localpv
remove storageClassName, this is unnecessary

2024-01-10 14:14 UTC, Slach commented on docs/chi-examples/02-templates-07-syncUser.yaml
> +      - name: local-pvc-my
rename to `data-pvc-template`

2024-01-12 08:49 UTC, ccsxs commented
@Slach Hello, I have revised and submitted it according to your comments,thanks.

2024-01-12 16:19 UTC, Slach approved these changes

2024-01-12 16:19 UTC, merged

2024-01-12 16:19 UTC, Slach commented
@ccsxs thanks for contribution