Default watch all Namespaces
Altinity/clickhouse-operator pull request #695
Opened 2021-05-07 03:18 UTC by TCeason

If config.WatchNamespaces is empty we should watch all Namseapces in the k8s.
https://github.com/Altinity/clickhouse-operator/issues/686

Thanks for taking the time to contribute to `clickhouse-operator`!

Please, read carefully [instructions on how to make a Pull Request](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#intro).

This will help a lot for maintainers to adopt your Pull Request. 

## Important items to consider before making a Pull Request
Please check items PR complies to:
* [ ] All commits in the PR are squashed. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#how-to-make-pr) 
* [ ] The PR is made into dedicated `next-release` branch, **not into** `master` branch<sup>1</sup>. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#how-to-make-pr)
* [ ] The PR is signed. [More info](https://github.com/Altinity/clickhouse-operator/blob/master/CONTRIBUTING.md#sign-your-work)

--

<sup>1</sup> If you feel your PR does not affect any Go-code or any testable functionality (for example, PR contains docs only or supplementary materials), PR can be made into `master` branch, but it has to be confirmed by project's maintainer.

2021-05-07 03:36 UTC, TCeason commented
@Slach  Please review this pr and present your opinion. Thanks.

2021-05-07 03:48 UTC, Slach commented
look like it will break behavior when you install separate clickhouse-operator to separate "tenant" namespace for multi-tenant kubernetes cluster like OpenShift

2021-05-07 03:54 UTC, TCeason commented
If so, how to resolve this question: https://github.com/Altinity/clickhouse-operator/issues/294?

2021-05-07 04:06 UTC, TCeason commented
The value of unspecified watchNamespaces should be the same as the value of specified kube-system.

Because :  In case no namespaces specified - watch all namespaces

```
// TODO unify with GetInformerNamespace
// IsWatchedNamespace returns whether specified namespace is in a list of watched
func (config *OperatorConfig) IsWatchedNamespace(namespace string) bool {
	// In case no namespaces specified - watch all namespaces
	if len(config.WatchNamespaces) == 0 {
		return true
	}

	return util.InArray(namespace, config.WatchNamespaces)
}

```

And befort this this pr only `namespace == "kube-system"` the len(config.WatchNamespaces) equal with 0.

2021-05-07 04:08 UTC, Slach commented
@sunsingerus @alex-zaitsev could share your opinion?

2021-05-12 01:02 UTC, TCeason commented
Ok, let me see

2021-05-12 04:53 UTC, Slach commented
@TCeason great ;) thanks a lot for your efforts!

2021-05-12 04:54 UTC, Slach requested changes
propose add regexp or glob support for watchNamespaces

2021-05-12 07:31 UTC, closed without merging